### ISSUE TITLE
Please update base URIs so that they are unique.

### ISSUE THREAD

**Issue by neilotte** [ufbmi/geographical-entity-ontology#17]
Most of the files in this repository have unique base URIs with the exception of:

- nation-and-dependency-instances.rdf
- us-mas-dependencies.rdf
- nation-instances.rdf

All of the generic base URI: http://www.w3.org/2002/07/owl

And:
- us-all-geography.rdf
- us-integral-geography.rdf

which both share a base URI:
http://purl.obolibrary.org/obo/geo/us-geography.owl

**Comment by hoganwr** [comment]
Thanks for catching this!  I fixed these issues on both development and master branches.  Please let me know if you see any additional issues.
