### ISSUE TITLE
OBO metadata is out of date for this ontology

### ISSUE THREAD

**Issue by cmungall** [ufbmi/geographical-entity-ontology#20]
http://obofoundry.org/ontology/geo

The tracker link is for a JIRA site that seems out of date

You can make a PR here to change this:
https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/geo.md

or contact me if you need help

**Comment by hoganwr** [comment]
This has been fixed.  The metadata file now has the following tracker entry:  https://github.com/ufbmi/geographical-entity-ontology/issues
