### ISSUE TITLE
definition missing: geographical entity

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/geographical-entity-ontology#4]

**Comment by hoganwr** [comment]
How about: "A material entity that is a bona fide or fiat object part of the Earth"

with the following disclaimer as an rdfs:comment "Includes atmosphere, crust, geographical regions (e.g., the geographical region over which the state of Florida has jurisdiction), bodies of water, mountains, etc.

Generally, an individual organism is a distinct object that is contained within, but not a part of, the Earth, although this requires more thought.  But the intent is definitely for this class to NOT subsume organism universally.  Human beings are contained within, but not part of, the Earth, for example."

**Comment by mbrochhausen** [comment]
This raises two questions:

1. Is the earth core (or a formation of bituminous coal 300 feet below the surface) a geographical entity? (maybe the intention is that the disclaimer takes care of that)
2. While being aware that we geo means Earth, I am wondering whether there is something like moon geography and Martian geography and whether this entity needs to cover those.

**Comment by hoganwr** [comment]
Mathias, I would have said "yes" to #1 but looking at various definitions of 'geography', I see that the answer is clearly "no".  #2 is less clear: definitions of 'geography' clearly restrict to Earth, but you see informal references to geography of moon and Mars, although the latter is also called 'areography'.  I'm happy to add an editor preferred term of "geographical entity of Earth".

Suggestions for revision of the definition to help with #1 are welcome.

**Comment by hoganwr** [comment]
It's still a bit over-inclusive, but we could define it as "A material entity that is a bona fide or fiat object part of the Earth's lithosphere, atmosphere, and/or hydrosphere."

The over-inclusive part is the entire lithosphere which includes the entire crust (already over-inclusive) and upper mantle.  Perhaps entire atmosphere is, too, but not as worried about that.

**Comment by mbrochhausen** [comment]
How about: "A material entity that is a bona fide or fiat object part of the Earth's surface, atmosphere, or hydrosphere."?

**Comment by mbrochhausen** [comment]
regarding #2: I think it is, of course, totally ok to restrict the domain of GEO to the earth. I am just wondering whether that is the best strategy. The matter raises some interesting questions. When I think about a geographical feature (I just noticed that class doesn't have a definition either), a thing that comes to mind is a crater. When we model 'crater' as a geographical feature, we would only model craters on Earth. However, isn't there a repeatable underlying all craters (including e.g. craters on the moon)? So, the class 'crater' in GEO would model all and only craters that are part of Earth and some other ontology would need to model craters in general. Again, that is a design decision we can make. I am just wondering whether we want to make it and whether maybe making GEO a geography ontology which uses geography in the broad and not in its restricted meaning makes more sense. Just throwing it out there.

**Comment by hoganwr** [comment]
I had the same thoughts about "mountain".  They tend to be the same thing on Earth, the Moon, Mars, etc.  If we use your definition, then how do we define 'surface'?  That's what I've been struggling with.  Geography includes atmospheric and oceanographic and other aspects that really encompass the atmosphere, hydrosphere, and the crust to a certain depth, although no one I've seen really specifies it.

**Comment by hoganwr** [comment]
So I'm willing to drop the restriction to Earth.  

A material entity that is a bona fide or fiat object part of the crust, atmosphere, or hydrosphere of planet or a planet's moon.

**Comment by hoganwr** [comment]
But then I'm not sure about "crust".  And Titan has ocean's that are not water, so it's more of a "liquid methane sphere" as opposed to "hydrosphere".

**Comment by dillerm** [comment]
It may be best to drop 'hydrosphere' and just refer to the surface of a planet or satellite. I think the closest thing to what you might be looking for is either going to be the crust or the [pedosphere](https://en.wikipedia.org/wiki/Pedosphere), although the latter seems a bit too jargony and may even be too exclusive. 

As such, it may be best to define a planetary surface as the portion of the crust or surface liquids of an astronomical object that comes in contact with the atmosphere or outer space.

**Comment by hoganwr** [comment]
I agree about dropping hydrosphere.  According this Wikipedia entry on "planetary surface", (1) crust includes solid and liquid portions and (2) natural satellites (aka moons) have a planetary surface (well not all of them necessarily, but nearly all anyway).

This article also references the planetary boundary layer, which is a good stopping point I think.

So, perhaps we could say "A material entity that is a bona fide or fiat object part of the crust or planetary boundary layer of a terrestrial planet (including Earth), dwarf planet, exoplanet, natural satellite, planetesimal, or Small Solar System body".  

Then in the comment we can say "Not all such astronomical objects necessarily have a crust or planetary boundary layer (for example, the gas giants Jupiter and Saturn).  So only those objects that have a crust with or without a planetary boundary layer have geographical entities as parts".

**Comment by hoganwr** [comment]
Been thinking some more:

A material entity that is (1) a bona fide or fiat object part of the crust, any bodies of liquid on or contained within the crust, or planetary boundary layer (if present) of a terrestrial planet (including Earth), dwarf planet, exoplanet, natural satellite, planetesimal, or small Solar System body, and that (2) overlaps the planetary surface (including having part of the planetary surface as a boundary).

We're not just talking about the surface as a geometrical plane or sheet.  When we talk of a mountain, it's a 3D thing.  Ditto for a river, lake, ocean.  So it can't just be planetary surface.

**Comment by mbrochhausen** [comment]
Yes, I agree on the surface issue. I like the definition you propose
