### ISSUE TITLE
definition missing: geographical region

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/geographical-entity-ontology#5]

**Comment by hoganwr** [comment]
This one is tricker, but here is what I came up with so far:

"A geopgraphical entity that is a fiat part of the Earth and that is demarcated by boundary lines specified by a map and which specify at every point a location at or near the bona fide boundary between (1) land or water and (2) the atmosphere."

**Comment by fmodave** [comment]
Guessing it would have to be a closed boundary

Fran?ois Modave, PhD
Associate Professor
Dept. Health Outcomes and Policy

On Jul 18, 2017, at 4:09 PM, Bill Hogan <notifications@github.com<mailto:notifications@github.com>> wrote:


This one is tricker, but here is what I came up with so far:

"A geopgraphical entity that is a fiat part of the Earth and that is demarcated by boundary lines specified by a map and which specify at every point a location at or near the bona fide boundary between (1) land or water and (2) the atmosphere."

-

**Comment by dillerm** [comment]
May also want to specify that geographical regions can also be demarcated by boundary lines that are defined by certain physical characteristics. For example, the geographical region of Lake Superior would be defined by both its shoreline, in addition to whatever lines were drawn to distinguish it from the mouths of one of its many tributaries and from the St. Mary's River.

**Comment by hoganwr** [comment]
Yes, one or more closed boundaries.  Because if you say the geographical region of U.S., you have lower 48 (one boundary), Alaska (another boundary), Hawaii (another boundary or set of boundaries depending on how it's defined), and Puerto Rico (one or more boundaries as it's more than one island), Guam, American Samoa, etc.

**Comment by hoganwr** [comment]
That's easily handled by saying the boundary is a mix of fiat and bona fide
components.

**Comment by hoganwr** [comment]
Given the discussion on the definition of 'geographical entity', I propose the following:

A geopgraphical entity that is demarcated at least in part by one or more closed boundaries all of whose lines are part of the planetary surface.

**Comment by mbrochhausen** [comment]
+1
